name : Caching and artifacts
on: [workflow_dispatch]

jobs:
    caching-job:
        runs-on: ${{vars.OS}}
        steps:
            - name: checking out to main branch
              uses: actions/checkout@v3
            - name : using cache action
              id : 'cache-id'
              uses: actions/cache@v3
              with :
                path: ~ /.npm
                key : 'npm-cache-key'
            - name : cache output
              run : echo '${{toJSON(steps.cache-id)}}'
            - name : install dependencies
              run: npm i
            - name : Use js github action
              uses : actions/github-script@v6
              with:
                script: |
                    const axios = require('axios');
                    const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
                    console.log(res.data)