name: checkout wf
on: [push]

jobs:
  checkout-action-marketplace:
    runs-on: ubuntu-latest
    steps:
    - name : files bfr
      run : ls -a
    - uses: actions/checkout@v4
    - name : files after
      run : ls -a
