name: dir and shell cmnds
on: [push]

jobs:
    display-wd-linux:
        runs-on: ubuntu-latest
        steps:
            - name: dir and shell -unix
              run : |
                pwd
                ls
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-windows:
        runs-on: windows-latest
        steps:
        - name: dir and shell -windows
          run : |
            Get-Location
            dir
            echo $env:GITHUB_SHA
            echo $env:GITHUB_REPOSITORY
            echo $env:GITHUB_WORKSPACE