name: Sample java app
on : [push]
jobs:
    java-app-build:
        runs-on: ubuntu-latest
        steps:
            - name : checkout to main branch
              uses : actions/checkout@v3 
            - name : Java app
              uses : actions/setup-java@v1
              with:
                java-version: 17
            - name : Caching Maven
              uses: actions/cache@v1
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            - name : Build maven 
              run : mvn clean install
            - name : List dir
              run : ls -a
            - name : List dir inside target folder
              run : |
                cd target
                ls -a
                pwd
                echo '${{ github.workspace }}'
            - name : Storing artifacts
              uses : actions/upload-artifact@v3
              with:
                name: maven-artifact
                path: '${{ github.workspace }}/target/*.jar'
    java-app-deploy:
        needs : java-app-build
        runs-on: ubuntu-latest
        steps:
            - name : artifact download
              uses : actions/download-artifact@v3
              with:
                name: maven-artifact
            - name : deploy to azure web apps
              uses : azure/webapps-deploy@v2
              with:
                app-name: "github-actions-assign-1"
                publish-profile : ${{secrets.AZURE_PUB_PROF_VASI}}
                package: '*.jar'
            - name : list the files after depoly
              run : ls -a
               
            