name : reusable wf for java app
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'input description-caller'
                type: string
                default : 'caller-name-details'
                required : false
jobs:
    Reusing-java-app-wf:
        runs-on: ubuntu-latest
        steps:
            - name : Calling the java app wf
              uses : github-actions-demo7/github_actions/.github/workflows/java-app.yml@main
              with:
                secrets: inherit