name: Sample java app
on : [push]
jobs:
    java-app:
        runs-on: ubuntu-latest
        steps:
            - name : checkout to main branch
              uses : actions/checkout@v3
            - name : Java app
              uses : actions/setup-java@v1
              with:
                java-version: 17
            - name : Caching Maven
              uses: actions/cache@v1
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            - name : Build maven 
              run : mvn -B package --file pom.xml
            - name : List dir
              run : ls -a
            - name : List dir inside target folder
              run : |
                cd target
                ls -a
                pwd
                echo '${{ github.workspace }}'
            - name : Storing artifacts
              uses : actions/upload-artifact@v3
              with:
                name: maven-artifact
                path: '${{ github.workspace }}/target/*.jar'
            
              
            

