name : Pull request
on: [pull_request]

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE