name : Variables and Secrets
on : [push]

jobs:
    var-secr:
        runs-on: ${{vars.OS}}
        steps:
            - name : variables and secrets definied
              run: |
                echo ${{secrets.REPO_SEC}}
                echo ${{vars.REPO_VAR}}


