name : Variables and Secrets
on : [push]
run-name: "Variables and Secrets run by @${{github.actor}} in the event of ${{github.event_name}}"
jobs:
    var-secr:
        runs-on: ${{vars.OS}}
        env: 
            REPO_VAR: ${{vars.REPO_SEC}}
            OS: ${{vars.OS}}

        steps:
            - name : variables and secrets definied
              run: |
                echo ${{secrets.REPO_SEC}}
                echo ${{vars.REPO_VAR}}
                echo ${{vars.OS}}
            - name : Context way of using variables
              run : |
                echo "REPO_VAR: $REPO_VAR"
                echo "REPO_OS: $REPO_OS"


